import { ArrowLeft, Check, Info, Ticket } from 'lucide-react';
import type { Movie, Seat, ShowTime } from '../data/movies';

interface Props { movie: Movie; showTime: ShowTime; seats: Seat[]; selectedSeats: string[]; onSelectSeat: (id: string) => void; onConfirm: () => void; onBack: () => void; }
export default function SeatSelector({ movie, showTime, seats, selectedSeats, onSelectSeat, onConfirm, onBack }: Props) {
  const rows = [...new Set(seats.map((seat) => seat.row))];
  const total = selectedSeats.length * 8.5;
  return <section className="mx-auto max-w-6xl"><button type="button" onClick={onBack} className="back-button"><ArrowLeft size={16} /> Cambiar función</button><div className="mt-7 grid gap-7 lg:grid-cols-[1fr_310px]"><div className="rounded-[2rem] bg-[#fffdf8] p-5 shadow-[0_16px_45px_rgba(25,23,23,.08)] sm:p-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e65335]">Sala 4 · {showTime.time}</p><h1 className="font-display mt-2 text-4xl">Elegí tus butacas</h1></div><span className="rounded-full bg-[#edf1ed] px-3 py-1.5 text-xs font-semibold text-[#254b42]"><Info className="mr-1 inline" size={14} /> Podés elegir hasta 6</span></div><div className="screen mt-10">Pantalla</div><div className="mt-9 overflow-x-auto pb-2"><div className="mx-auto w-max space-y-3">{rows.map((row) => <div key={row} className="flex items-center gap-3"><span className="w-4 text-xs font-bold text-[#746d66]">{row}</span><div className="flex gap-2">{seats.filter((seat) => seat.row === row).map((seat, index) => <button key={seat.id} type="button" disabled={seat.status === 'occupied'} onClick={() => onSelectSeat(seat.id)} aria-label={`Asiento ${seat.id}, ${seat.status === 'occupied' ? 'ocupado' : selectedSeats.includes(seat.id) ? 'seleccionado' : 'disponible'}`} className={`seat ${seat.status === 'occupied' ? 'seat-occupied' : selectedSeats.includes(seat.id) ? 'seat-selected' : 'seat-free'} ${index === 4 ? 'mr-5' : ''}`}>{seat.number}</button>)}</div></div>)}</div></div><div className="mt-8 flex flex-wrap justify-center gap-x-6 gap-y-3 text-xs text-[#645d56]"><span><i className="legend seat-free" />Disponible</span><span><i className="legend seat-selected" />Seleccionada</span><span><i className="legend seat-occupied" />Ocupada</span></div></div><aside className="h-fit rounded-[2rem] bg-[#1d2927] p-6 text-white lg:sticky lg:top-5"><Ticket className="text-[#f5bd55]" size={22} /><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-[#b5c2bc]">Tu reserva</p><h2 className="font-display mt-2 text-3xl">{movie.title}</h2><p className="mt-2 text-sm text-[#c9d2cc]">Hoy · {showTime.time} · Sala 4</p><div className="my-6 border-t border-white/15" /><div className="flex items-end justify-between"><div><p className="text-xs text-[#b5c2bc]">Butacas</p><p className="mt-1 font-semibold">{selectedSeats.length ? selectedSeats.join(', ') : 'Elegí tus lugares'}</p></div><p className="font-display text-2xl">Bs {total.toFixed(2)}</p></div><button type="button" disabled={!selectedSeats.length} onClick={onConfirm} className="mt-7 flex w-full items-center justify-center gap-2 rounded-full bg-[#f5bd55] px-5 py-3.5 text-sm font-bold text-[#1d2927] transition hover:bg-[#ffd275] disabled:cursor-not-allowed disabled:opacity-40"><Check size={17} /> Confirmar reserva</button></aside></div></section>;
}
